# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=50, null=True),
        ),
    ]
