# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171108_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Patanjali', 'PATANJALI'), ('Haldiram', 'HALDIRAM'), ('HUL', 'HUL'), ('Nestle', 'NESTLE'), ('Dabur', 'DABUR'), ('ITC', 'ITC'), ('Others', 'OTHERS')], default='Others', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cleaning Accessories', 'CLEANING ACCESSORIES'), ('Plastic ware', 'PLASTIC WARE'), ('Electrical ', 'ELECTRICAL '), ('Stationary', 'STATIONARY'), ('Utensils ', 'UTENSILS '), ('Biscuit and Snacks ', 'BISCUIT AND SNACKS '), ('Cereals and Grains ', 'CEREALS AND GRAINS '), ('Other Groceries ', 'OTHER GROCERIES '), ('Personal Care  ', 'PERSONAL CARE  '), ('Beverages ', 'BEVERAGES '), ('Bags ', 'BAGS '), ('Others ', 'OTHERS ')], default='Others', max_length=120),
        ),
    ]
