# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171109_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_raw',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
