# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_image_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_raw',
            new_name='raw_image',
        ),
    ]
